### ISSUE TITLE
Tuning

### ISSUE THREAD

**Issue by mlap** [boettiger-lab/gym_fishing#14]
Just wanted to get a thread going for potential tuning concerns. If using stable-baselines3, there is fortunately a RL-zoo that is compatible with stable-baselines 3: [https://github.com/DLR-RM/rl-baselines3-zoo/blob/master/utils/hyperparams_opt.py](https://github.com/DLR-RM/rl-baselines3-zoo/blob/master/utils/hyperparams_opt.py). I have not played around with this yet, but it will definitely taking some digging/editing to get a working tuning script going. 

(The link I previously sent on slack uses stable-baselines2, so I just wanted to clarify any potential problems that would come up here.)

**Comment by mlap** [comment]
Update: In `examples/marcus`, I have some tuning scripts that can be used with stable baselines 3. If anyone needs help here let me know.

**Comment by cboettig** [comment]
(tuning examples moved to https://github.com/boettiger-lab/conservation-agents)
